name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Build & test
        run: |
          npm ci
          npm run lint
          npm run build
          npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
